### ISSUE TITLE
Creata icon

### ISSUE THREAD

**Issue by BolotinAlexey** [React2024Q3/graphiql-app#7]
I created icons for the site, it is also an icon for the organization, as well as a logo (possibly animated in Header/Footer). If anyone has suggestions for improvement, offer.

![Image](https://github.com/user-attachments/assets/13b67e39-a08b-4cce-a8bf-1242cf306e26)

**Comment by BolotinAlexey** [comment]
I created icons for the site, it is also an icon for the organization, as well as a logo (possibly animated in Header/Footer). If anyone has suggestions for improvement, offer.


![Image](https://github.com/user-attachments/assets/13b67e39-a08b-4cce-a8bf-1242cf306e26)

**Comment by freennnn** [comment]
Done
